apiVersion: v1
kind: Secret
metadata:
  name: booking-postgres-secret
  namespace: booking
type: Opaque
stringData:
  POSTGRES_DB: bookingdb-bookings
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
