apiVersion: v1
kind: Secret
metadata:
  name: invoice-postgres-secret
  namespace: booking
type: Opaque
stringData:
  POSTGRES_DB: bookingdb-invoices
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password
