apiVersion: v1
kind: Secret
metadata:
  name: user-service-secret
  namespace: booking
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
  REDIS_PASSWORD: redispass
  MONGO_PASSWORD: rootpass
  RABBITMQ_PASS: guest
  JWT_SECRET: fJ8z2vK6yQ3pX9mR4wT5sN7bE1uI0aH8oL2cD6gV4eK3=
