apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: booking-postgres
  namespace: booking
spec:
  serviceName: booking-postgres
  replicas: 1
  selector:
    matchLabels:
      app: booking-postgres
  template:
    metadata:
      labels:
        app: booking-postgres
    spec:
      containers:
        - name: booking-postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: booking-postgres-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "user"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "user"]
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: booking-postgres-data
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: booking-postgres-data
          persistentVolumeClaim:
            claimName: booking-postgres-pvc
