apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: provider-postgres
  namespace: booking
spec:
  serviceName: provider-postgres
  replicas: 1
  selector:
    matchLabels:
      app: provider-postgres
  template:
    metadata:
      labels:
        app: provider-postgres
    spec:
      containers:
        - name: provider-postgres
          image: postgres:17
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: provider-postgres-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "user"]
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["pg_isready", "-U", "user"]
            initialDelaySeconds: 15
            periodSeconds: 20
          volumeMounts:
            - name: provider-postgres-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: provider-postgres-data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: local-path
        resources:
          requests:
            storage: 1Gi
